/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    posts: Post
    'autosave-posts': AutosavePost
    'draft-posts': DraftPost
    'version-posts': VersionPost
    users: User
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  globals: {
    'autosave-global': AutosaveGlobal
    'draft-global': DraftGlobal
  }
}
export interface Post {
  id: string
  relationToVersions?: string | VersionPost
  relationToDrafts?: string | DraftPost
  updatedAt: string
  createdAt: string
}
export interface VersionPost {
  id: string
  title: string
  description: string
  updatedAt: string
  createdAt: string
}
export interface DraftPost {
  id: string
  title: string
  description: string
  radio?: 'test'
  select?: ('test1' | 'test2')[]
  blocksField?: {
    text?: string
    localized?: string
    id?: string
    blockName?: string
    blockType: 'block'
  }[]
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface AutosavePost {
  id: string
  title: string
  description: string
  updatedAt: string
  createdAt: string
  _status?: 'draft' | 'published'
}
export interface User {
  id: string
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string
  resetPasswordExpiration?: string
  salt?: string
  hash?: string
  loginAttempts?: number
  lockUntil?: string
  password: string
}
export interface PayloadPreference {
  id: string
  user: {
    relationTo: 'users'
    value: string | User
  }
  key?: string
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
export interface PayloadMigration {
  id: string
  name?: string
  batch?: number
  updatedAt: string
  createdAt: string
}
export interface AutosaveGlobal {
  id: string
  title: string
  _status?: 'draft' | 'published'
  updatedAt?: string
  createdAt?: string
}
export interface DraftGlobal {
  id: string
  title: string
  _status?: 'draft' | 'published'
  updatedAt?: string
  createdAt?: string
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
